// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oclddzfozikyvpkoifvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbGRkemZvemlreXZwa29pZnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODMyMjIsImV4cCI6MjA2OTM1OTIyMn0.0ImW733Us6FHooZ2re5p83ZnadktIoXYlbeGkfpabXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});